# Numpy ndarray

* * *

In [2]:
import numpy as np

## ndarray - Indexing
: Array indexing is the same as accessing an array element.
* slicing indexing
* fancy indexing - return the value of index
* boolean indexing - return with filted by condition

In [3]:
# 1D ndarray from 1 to 9
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [4]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index value:', array2d[0,0] )
print('(row=0,col=1) index value:', array2d[0,1] )
print('(row=1,col=0) index value:', array2d[1,0] )
print('(row=2,col=2) index value:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index value: 1
(row=0,col=1) index value: 2
(row=1,col=0) index value: 4
(row=2,col=2) index value: 9


## ndarray - slicing
* only consecutive index 

In [5]:
# slicing indexing (1D)
array1 = np.arange(start=1, stop=10)

# index : 0-2
array4 = array1[0:3]
print(array4)

# index : 3 to length-1
array5 = array1[3:]
print(array5)

# from 0 to length-1
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [8]:
# slicing indexing (2D)
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


## ndarray - fancy indexing


In [10]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


## ndarray - boolean indexing


In [11]:
array1d = np.arange(start=1, stop=10)
print(array1d)

# In [ ], the codition : array1d > 5 applied for Boolean indexing
array3 = array1d[array1d > 5]
print('array1d > 5 result of boolean indexing :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 result of boolean indexing : [6 7 8 9]


In [13]:
array1d > 5
val = array1d > 5
print(val, type(val), val.shape)

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [15]:
# the case which is not using boolean indexing 1: same result, but code is long! 

array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [16]:
# the case which is not using boolean indexing 2 : use general indexing

indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('the result :',array4)

the result : [6 7 8 9]
