# Numpy ndarray

* * *

In [4]:
import numpy as np

## NumPy Array Shape

In [5]:
list1 = [1, 2, 3]
print('list1 type:', type(list1))
array1 = np.array(list1)
#array1 = np.array([1,2,3])

print('array1 type:',type(array1))
print('array1 array shape:',array1.shape)
#array1 shape = (3,) 

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array shape:',array2.shape)
#array2 shape = (2,3) 

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array shape:',array3.shape)
#array3 shape = (1,3) 


list1 type: <class 'list'>
array1 type: <class 'numpy.ndarray'>
array1 array shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array shape: (1, 3)


In [6]:
print('array1:{:0} dimension, array2:{:1} dimension, array3:{:2} dimension'.format(array1.ndim,array2.ndim,array3.ndim))
 

array1:1 dimension, array2:2 dimension, array3: 2 dimension


## ndarray's data type

In [8]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
#array1's type : numpy.ndarray

print(array1, array1.dtype)
#data type = int64


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


 ### **In ndarray, the data type should be same!**
 * different data type can be inserted but it should be type casting


In [12]:
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# automatic type casting to string(U21)

['1' '2' 'test'] <U21


In [14]:
list3 = [1,2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

# Automatic type casting to float(float64)

[1. 2. 3.] float64


In [17]:
array_int = np.array([1,2,3])

# array_int.astype(np.float64)
array_float = array_int.astype('float64')

print(array_int, array_float.dtype)


[1 2 3] float64


In [18]:
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [19]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32
