# Numpy ndarray

* * *

In [3]:
import numpy as np

## Creating easilty with ndarray ( arange, zeros, ones )

In [7]:
#range (0 ~ 9)
sequence_array = np.arange(10)

print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

#(3, 2) shape's all element is 0, dtype = int32 
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#(3, 2) shape's all element is 1
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray - reshape

In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

# array1 reshape to (2, 5) 
array2 = array1.reshape(2,5)
print('array2:\n', array2)

# array2 reshape to (5, 2) 
array3 = array1.reshape(5,2)
print('array3:\n',array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


 ### **In reshape(), unknown dimension is possible => -1 !**
 * Pass -1 as the value, and NumPy will calculate this number. 


In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
# NOT possible case in reshape()
array1.reshape(4,3)

array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [17]:
# (-1,) = 1D, (-1,1) = 2D

# 1D to 2D
array1 = np.arange(5)
print(array1)

# array2's shape will be (5,1) -> 2D
array2 = array1.reshape(-1,1)
print(array2)


# 2D to 1D
# array2's shape will be (5,) -> 1D
array3 = array2.reshape(-1,)
print(array3) 


[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[0 1 2 3 4]
