# Numpy ndarray

* * *

In [2]:
import numpy as np

## NumPy Sorting Arrays
* sort( )
* argsort( )

## Sorting - sort( )

In [9]:
org_array = np.array([ 3, 1, 9, 5]) 
print('original array:', org_array)

# np.sort( ) 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) :', sort_array1)

# the orginal array is not changing
print('np.sort( ) :', org_array)

# ndarray.sort( )
org_array.sort()
print('org_array.sort( ) :', org_array)



original array: [3 1 9 5]
np.sort( ) : [1 3 5 9]
np.sort( ) : [3 1 9 5]
org_array.sort( ) : [1 3 5 9]


In [6]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('descending order:', sort_array1_desc) 

descending order: [9 5 3 1]


In [11]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('row:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column:\n', sort_array2d_axis1)

row:
 [[ 7  1]
 [ 8 12]]
column:
 [[ 8 12]
 [ 1  7]]


## Sorting - argsort( )
* It returns an array of indices of the same shape as arr that would sort the array. 

In [12]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('after argsort the index of org_array:', sort_indices)

<class 'numpy.ndarray'>
after argsort the index of org_array: [1 0 3 2]


In [13]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('after descending order argsort the index of org_array:', sort_indices_desc)

after descending order argsort the index of org_array: [2 3 0 1]


In [21]:

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('ascending order sorting for score_array index:', sort_indices_asc)
print('the name based on ascending order sorting:', name_array[sort_indices_asc])

ascending order sorting for score_array index: [0 2 4 1 3]
the name based on ascending order sorting: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## NumPy - linear algebra
* dot()
* transpose()


In [22]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('result:\n', dot_product)

result:
 [[ 58  64]
 [139 154]]


In [23]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('the traspose array for A:\n', transpose_mat)

the traspose array for A:
 [[1 3]
 [2 4]]
